server:
  port: ${PORT:8000}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: '*'
#  host:
#   connect-timeout-millis: 20000
#   socket-timeout-millis: 20000
  prefix: /api
  routes:
    auth-server:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
    organization-service:
      path: /organization/**
      sensitiveHeaders:
      serviceId: organization-service
    email-service:
      path: /email/**
      serviceId: email-service
    storage-service:
      path: /storage/**
      sensitiveHeaders:
      serviceId: storage-service
  add-proxy-headers: true

security:
  oauth2:
    client:
      access-token-uri: http://${auth-server:localhost}:8000/api/uaa/oauth/token
      user-authorization-uri: http://${auth-server:localhost}:8000/api/uaa/oauth/authorize
    resource:
      user-info-uri: http://${auth-server:localhost}:8000/api/uaa/me
      prefer-token-info: false


eureka:
  instance:
    prefer-ip-address: ${PREFER_IP_ADDRESS}
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_USER}:${DISCOVERY_SERVICE_PASSWORD}@${EUREKA_HOSTNAME}:8761/eureka/