spring:
  data:
    mongodb:
      database: e_ppt_storage
      host: localhost
      port: 27017
      username: ${MES_USER}
      password: ${MES_PASSWORD}
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8004
  session:
    cookie:
      http-only: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_USER}:${DISCOVERY_SERVICE_PASSWORD}@${EUREKA_HOSTNAME}:8761/eureka/
  instance:
    prefer-ip-address: ${PREFER_IP_ADDRESS}
    # leaseRenewalIntervalInSeconds: 10
    # leaseExpirationDurationInSeconds: 2
    # instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}

security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: eppt
      user-info-uri: http://${auth-server:localhost}:8000/api/uaa/me
      filter-order: 3
      prefer-token-info: false

endpoints:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800

management:
  security:
    enabled: false