security:
  oauth2:
    client:
      client-id: account-service
      client-secret: 123456
      access-token-uri: http://localhost:8001/uaa/oauth/token
      grant-type: client_credentials
      scope: server
      user-authorization-uri: http://localhost:8001/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:8001/uaa/users/current
server:
  port: ${PORT:8002}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${discovery-service:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 2
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
spring:
  kafka:
    bootstrap-servers: localhost:9092

#hystrix:
#  command:
#    email-service:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000