server:
  port: ${PORT:8003}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${discovery-service:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 2
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
spring:
  kafka:
    bootstrap-servers: localhost:9092
  mail:
      host: smtp.gmail.com
      port: 587
      username: aseprojali@gmail.com
      password: jhf33cgmh2
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000