spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/espt?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: password
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  jackson:
    serialization.indent_output: true
    serialization.write_dates_as_timestamps: false
server:
  # port: 8002
  session:
    cookie:
      http-only: true

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   serviceUrl:
     defaultZone: http://${DISCOVERY_SERVICE_USER}:${DISCOVERY_SERVICE_PASSWORD}@${EUREKA_HOSTNAME}:8761/eureka/
 instance:
   prefer-ip-address: ${PREFER_IP_ADDRESS}
security:
 oauth2:
   resource:
     filter-order: 3

endpoints:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800